### ISSUE TITLE
3e vs 3ge

### ISSUE THREAD

**Issue by NihadBadalov** [xuyanshi/CSAPP#1]
Hey @xuyanshi, how're you doing?

I hope this issue finds you well. (haha)

Stumbled upon your repo and wanted to download the pdfs.
Just wanted to know what the difference is between 3rd edition and 3rd _global_ edition - couldn't find anything anywhere.

Thanks in advance.

Regards,
Nihad Badalov

**Comment by xuyanshi** [comment]
> Hey @xuyanshi, how're you doing?
> 
> I hope this issue finds you well. (haha)
> 
> Stumbled upon your repo and wanted to download the pdfs. Just wanted to know what the difference is between 3rd edition and 3rd _global_ edition - couldn't find anything anywhere.
> 
> Thanks in advance.
> 
> Regards, Nihad Badalov

Hi @NihadBadalov, I've searched your question on some Chinese websites.

In short, you'd better read the 3rd edition but **not** the 3rd global edition.

This is the official explanation:

> Note on the Global Edition: Unfortunately, the publisher arranged for the generation of a different set of practice and homework problems in the global edition. The person doing this didn’t do a very good job, and so these problems and their solutions have many errors. We have not created an errata for this edition.

References: 
- [https://csapp.cs.cmu.edu/3e/errata.html](https://csapp.cs.cmu.edu/3e/errata.html)
- [https://log.cryz.xyz/archives/1546](https://log.cryz.xyz/archives/1546)
